apiVersion: v1
kind: Service
metadata:
  name: weatherapp-service
  labels:
    name: weatherapp-service
    app: demo-voting-app
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
      name: weatherapi-pod
      app: demo-voting-app
      